# Generated by Django 3.0.7 on 2023-03-26 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('codigo', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo_produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loja.PedidoTipo'),
        ),
    ]
